- stage: 'DeployDev'
  displayName: 'Deploy to dev environment'
  dependsOn: Build
     pool:
      vmImage: 'Ubuntu-16.04'
   
    variables:
    - group: 'Release Pipeline'
   
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '$(WebAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
